from typing import *


# TODO: Maintaining this may be too much work - consider just loading dynamically based on type


class ObjectType:
  def __init__(
    self,
    name: str,
    behavior: List[str],
  ) -> None:
    self.name = name
    self.behavior = behavior

  def __repr__(self):
    return 'ObjectType(' + self.name + ')'


OBJECT_TYPES = [
  ObjectType(
    'StarDoor',
    ['bhvStarDoor'],
  ),
  ObjectType(
    'MrI',
    ['bhvMrI'],
  ),
  ObjectType(
    'MrIBody',
    ['bhvMrIBody'],
  ),
  ObjectType(
    'MrIParticle',
    ['bhvMrIParticle'],
  ),
  ObjectType(
    'GiantPiranhaParticle',
    ['bhvGiantPiranhaParticle'],
  ),
  ObjectType(
    'GiantPole',
    ['bhvGiantPole'],
  ),
  ObjectType(
    'PoleGrabbing',
    ['bhvPoleGrabbing'],
  ),
  ObjectType(
    'ThiHugeIslandTop',
    ['bhvThiHugeIslandTop'],
  ),
  ObjectType(
    'ThiTinyIslandTop',
    ['bhvThiTinyIslandTop'],
  ),
  ObjectType(
    'CapSwitchBase',
    ['bhvCapSwitchBase'],
  ),
  ObjectType(
    'CapSwitch',
    ['bhvCapSwitch'],
  ),
  ObjectType(
    'KingBobomb',
    ['bhvKingBobomb'],
  ),
  ObjectType(
    'BobombAnchorMario',
    ['bhvBobombAnchorMario'],
  ),
  ObjectType(
    'BetaChest',
    ['bhvBetaChest'],
  ),
  ObjectType(
    'BetaChestUpper',
    ['bhvBetaChestUpper'],
  ),
  ObjectType(
    'BubbleMario',
    ['bhvBubbleMario'],
  ),
  ObjectType(
    'BubbleMaybe',
    ['bhvBubbleMaybe'],
  ),
  ObjectType(
    'SmallWaterWave',
    ['bhvSmallWaterWave'],
  ),
  ObjectType(
    'SmallWaterWave398',
    ['bhvSmallWaterWave398'],
  ),
  ObjectType(
    'WaterAirBubble',
    ['bhvWaterAirBubble'],
  ),
  ObjectType(
    'SmallParticle',
    ['bhvSmallParticle'],
  ),
  ObjectType(
    'WaterWaves',
    ['bhvWaterWaves'],
  ),
  ObjectType(
    'SmallParticleSnow',
    ['bhvSmallParticleSnow'],
  ),
  ObjectType(
    'SmallParticleBubbles',
    ['bhvSmallParticleBubbles'],
  ),
  ObjectType(
    'FishGroup',
    ['bhvFishGroup'],
  ),
  ObjectType(
    'Cannon',
    ['bhvCannon'],
  ),
  ObjectType(
    'CannonBarrel',
    ['bhvCannonBarrel'],
  ),
  ObjectType(
    'CannonBaseUnused',
    ['bhvCannonBaseUnused'],
  ),
  ObjectType(
    'Chuckya',
    ['bhvChuckya'],
  ),
  ObjectType(
    'ChuckyaAnchorMario',
    ['bhvChuckyaAnchorMario'],
  ),
  ObjectType(
    'Unused05A8',
    ['bhvUnused05A8'],
  ),
  ObjectType(
    'RotatingPlatform',
    ['bhvRotatingPlatform'],
  ),
  ObjectType(
    'Tower',
    ['bhvTower'],
  ),
  ObjectType(
    'BulletBillCannon',
    ['bhvBulletBillCannon'],
  ),
  ObjectType(
    'WfBreakableWallRight',
    ['bhvWfBreakableWallRight'],
  ),
  ObjectType(
    'WfBreakableWallLeft',
    ['bhvWfBreakableWallLeft'],
  ),
  ObjectType(
    'KickableBoard',
    ['bhvKickableBoard'],
  ),
  ObjectType(
    'TowerDoor',
    ['bhvTowerDoor'],
  ),
  ObjectType(
    'RotatingCounterClockwise',
    ['bhvRotatingCounterClockwise'],
  ),
  ObjectType(
    'WfRotatingWoodenPlatform',
    ['bhvWfRotatingWoodenPlatform'],
  ),
  ObjectType(
    'KoopaShellUnderwater',
    ['bhvKoopaShellUnderwater'],
  ),
  ObjectType(
    'ExitPodiumWarp',
    ['bhvExitPodiumWarp'],
  ),
  ObjectType(
    'FadingWarp',
    ['bhvFadingWarp'],
  ),
  ObjectType(
    'Warp',
    ['bhvWarp'],
  ),
  ObjectType(
    'WarpPipe',
    ['bhvWarpPipe'],
  ),
  ObjectType(
    'WhitePuffExplosion',
    ['bhvWhitePuffExplosion'],
  ),
  ObjectType(
    'SpawnedStar',
    ['bhvSpawnedStar'],
  ),
  ObjectType(
    'Unused080C',
    ['bhvUnused080C'],
  ),
  ObjectType(
    'MrIBlueCoin',
    ['bhvMrIBlueCoin'],
  ),
  ObjectType(
    'CoinInsideBoo',
    ['bhvCoinInsideBoo'],
  ),
  ObjectType(
    'CoinFormationSpawn',
    ['bhvCoinFormationSpawn'],
  ),
  ObjectType(
    'CoinFormation',
    ['bhvCoinFormation'],
  ),
  ObjectType(
    'OneCoin',
    ['bhvOneCoin'],
  ),
  ObjectType(
    'YellowCoin',
    ['bhvYellowCoin'],
  ),
  ObjectType(
    'TemporaryYellowCoin',
    ['bhvTemporaryYellowCoin'],
  ),
  ObjectType(
    'ThreeCoinsSpawn',
    ['bhvThreeCoinsSpawn'],
  ),
  ObjectType(
    'TenCoinsSpawn',
    ['bhvTenCoinsSpawn'],
  ),
  ObjectType(
    'SingleCoinGetsSpawned',
    ['bhvSingleCoinGetsSpawned'],
  ),
  ObjectType(
    'CoinSparkles',
    ['bhvCoinSparkles'],
  ),
  ObjectType(
    'GoldenCoinSparkles',
    ['bhvGoldenCoinSparkles'],
  ),
  ObjectType(
    'WallTinyStarParticle',
    ['bhvWallTinyStarParticle'],
  ),
  ObjectType(
    'WallTinyStarParticleSpawn',
    ['bhvWallTinyStarParticleSpawn'],
  ),
  ObjectType(
    'PoundTinyStarParticle',
    ['bhvPoundTinyStarParticle'],
  ),
  ObjectType(
    'PoundTinyStarParticleSpawn',
    ['bhvPoundTinyStarParticleSpawn'],
  ),
  ObjectType(
    'PunchTinyTriangle',
    ['bhvPunchTinyTriangle'],
  ),
  ObjectType(
    'PunchTinyTriangleSpawn',
    ['bhvPunchTinyTriangleSpawn'],
  ),
  ObjectType(
    'DoorWarp',
    ['bhvDoorWarp'],
  ),
  ObjectType(
    'Door',
    ['bhvDoor'],
  ),
  ObjectType(
    'Grindel',
    ['bhvGrindel'],
  ),
  ObjectType(
    'Thwomp2',
    ['bhvThwomp2'],
  ),
  ObjectType(
    'Thwomp',
    ['bhvThwomp'],
  ),
  ObjectType(
    'TumblingBridgePlatform',
    ['bhvTumblingBridgePlatform'],
  ),
  ObjectType(
    'WfTumblingBridge',
    ['bhvWfTumblingBridge'],
  ),
  ObjectType(
    'BbhTumblingBridge',
    ['bhvBbhTumblingBridge'],
  ),
  ObjectType(
    'LllTumblingBridge',
    ['bhvLllTumblingBridge'],
  ),
  ObjectType(
    'Flame',
    ['bhvFlame'],
  ),
  ObjectType(
    'AnotherElavator',
    ['bhvAnotherElavator'],
  ),
  ObjectType(
    'RrElevatorPlatform',
    ['bhvRrElevatorPlatform'],
  ),
  ObjectType(
    'HmcElevatorPlatform',
    ['bhvHmcElevatorPlatform'],
  ),
  ObjectType(
    'WaterMist',
    ['bhvWaterMist'],
  ),
  ObjectType(
    'WaterMistSpawn',
    ['bhvWaterMistSpawn'],
  ),
  ObjectType(
    'BreakBoxTriangle',
    ['bhvBreakBoxTriangle'],
  ),
  ObjectType(
    'WaterMist2',
    ['bhvWaterMist2'],
  ),
  ObjectType(
    'Unused0DFC',
    ['bhvUnused0DFC'],
  ),
  ObjectType(
    'PoundWhitePuffs',
    ['bhvPoundWhitePuffs'],
  ),
  ObjectType(
    'GroundSand',
    ['bhvGroundSand'],
  ),
  ObjectType(
    'Unused0E40',
    ['bhvUnused0E40'],
  ),
  ObjectType(
    'GroundSnow',
    ['bhvGroundSnow'],
  ),
  ObjectType(
    'Wind',
    ['bhvWind'],
  ),
  ObjectType(
    'EndToad',
    ['bhvEndToad'],
  ),
  ObjectType(
    'EndPeach',
    ['bhvEndPeach'],
  ),
  ObjectType(
    'PiranhaParticlesSpawn',
    ['bhvPiranhaParticlesSpawn'],
  ),
  ObjectType(
    'Ukiki',
    ['bhvUkiki'],
  ),
  ObjectType(
    'Unused0F14',
    ['bhvUnused0F14'],
  ),
  ObjectType(
    'LittleCage2',
    ['bhvLittleCage2'],
  ),
  ObjectType(
    'LittleCage',
    ['bhvLittleCage'],
  ),
  ObjectType(
    'BitfsSinkingPlatforms',
    ['bhvBitfsSinkingPlatforms'],
  ),
  ObjectType(
    'BitfsSinkingCagePlatform',
    ['bhvBitfsSinkingCagePlatform'],
  ),
  ObjectType(
    'DddMovingPole',
    ['bhvDddMovingPole'],
  ),
  ObjectType(
    'BitfsTiltingSquarePlatform',
    ['bhvBitfsTiltingSquarePlatform'],
  ),
  ObjectType(
    'SquishablePlatform',
    ['bhvSquishablePlatform'],
  ),
  ObjectType(
    'CutOutObject',
    ['bhvCutOutObject'],
  ),
  ObjectType(
    'BetaMovingFlamesSpawn',
    ['bhvBetaMovingFlamesSpawn'],
  ),
  ObjectType(
    'BetaMovingFlames',
    ['bhvBetaMovingFlames'],
  ),
  ObjectType(
    'RrRotatingBridgePlatform',
    ['bhvRrRotatingBridgePlatform'],
  ),
  ObjectType(
    'Flamethrower',
    ['bhvFlamethrower'],
  ),
  ObjectType(
    'FlamethrowerFlame',
    ['bhvFlamethrowerFlame'],
  ),
  ObjectType(
    'BouncingFireball',
    ['bhvBouncingFireball'],
  ),
  ObjectType(
    'BouncingFireballFlame',
    ['bhvBouncingFireballFlame'],
  ),
  ObjectType(
    'BowserShockWave',
    ['bhvBowserShockWave'],
  ),
  ObjectType(
    'FlameMario',
    ['bhvFlameMario'],
  ),
  ObjectType(
    'BlackSmokeMario',
    ['bhvBlackSmokeMario'],
  ),
  ObjectType(
    'BlackSmokeBowser',
    ['bhvBlackSmokeBowser'],
  ),
  ObjectType(
    'BlackSmokeUpward',
    ['bhvBlackSmokeUpward'],
  ),
  ObjectType(
    'BetaFishSplashSpawner',
    ['bhvBetaFishSplashSpawner'],
  ),
  ObjectType(
    'Spindrift',
    ['bhvSpindrift'],
  ),
  ObjectType(
    'TowerPlatformGroup',
    ['bhvTowerPlatformGroup'],
  ),
  ObjectType(
    'WfSlidingTowerPlatform',
    ['bhvWfSlidingTowerPlatform'],
  ),
  ObjectType(
    'WfElevatorTowerPlatform',
    ['bhvWfElevatorTowerPlatform'],
  ),
  ObjectType(
    'WfSolidTowerPlatform',
    ['bhvWfSolidTowerPlatform'],
  ),
  ObjectType(
    'SnowLeafParticleSpawn',
    ['bhvSnowLeafParticleSpawn'],
  ),
  ObjectType(
    'TreeSnow',
    ['bhvTreeSnow'],
  ),
  ObjectType(
    'TreeLeaf',
    ['bhvTreeLeaf'],
  ),
  ObjectType(
    'AnotherTiltingPlatform',
    ['bhvAnotherTiltingPlatform'],
  ),
  ObjectType(
    'SquarishPathMoving',
    ['bhvSquarishPathMoving'],
  ),
  ObjectType(
    'PiranhaPlantBubble',
    ['bhvPiranhaPlantBubble'],
  ),
  ObjectType(
    'PiranhaPlantWakingBubbles',
    ['bhvPiranhaPlantWakingBubbles'],
  ),
  ObjectType(
    'FloorSwitchAnimatesObject',
    ['bhvFloorSwitchAnimatesObject'],
  ),
  ObjectType(
    'FloorSwitchGrills',
    ['bhvFloorSwitchGrills'],
  ),
  ObjectType(
    'FloorSwitchHardcodedModel',
    ['bhvFloorSwitchHardcodedModel'],
  ),
  ObjectType(
    'FloorSwitchHiddenObjects',
    ['bhvFloorSwitchHiddenObjects'],
  ),
  ObjectType(
    'HiddenObject',
    ['bhvHiddenObject'],
  ),
  ObjectType(
    'BreakableBox',
    ['bhvBreakableBox'],
  ),
  ObjectType(
    'PushableMetalBox',
    ['bhvPushableMetalBox'],
  ),
  ObjectType(
    'HeaveHo',
    ['bhvHeaveHo'],
  ),
  ObjectType(
    'HeaveHoThrowMario',
    ['bhvHeaveHoThrowMario'],
  ),
  ObjectType(
    'CcmTouchedStarSpawn',
    ['bhvCcmTouchedStarSpawn'],
  ),
  ObjectType(
    'PoundExplodes',
    ['bhvPoundExplodes'],
  ),
  ObjectType(
    'BetaTrampoline',
    ['bhvBetaTrampoline'],
  ),
  ObjectType(
    'BetaTrampolineSpawn',
    ['bhvBetaTrampolineSpawn'],
  ),
  ObjectType(
    'JumpingBox',
    ['bhvJumpingBox'],
  ),
  ObjectType(
    'BooCage',
    ['bhvBooCage'],
  ),
  ObjectType(
    'Stub',
    ['bhvStub'],
  ),
  ObjectType(
    'Igloo',
    ['bhvIgloo'],
  ),
  ObjectType(
    'BowserKey2',
    ['bhvBowserKey2'],
  ),
  ObjectType(
    'GrandStar',
    ['bhvGrandStar'],
  ),
  ObjectType(
    'BetaBooKeyInside',
    ['bhvBetaBooKeyInside'],
  ),
  ObjectType(
    'BetaBooKeyOutside',
    ['bhvBetaBooKeyOutside'],
  ),
  ObjectType(
    'BulletBill',
    ['bhvBulletBill'],
  ),
  ObjectType(
    'WhitePuffSmoke',
    ['bhvWhitePuffSmoke'],
  ),
  ObjectType(
    'Unused1820',
    ['bhvUnused1820'],
  ),
  ObjectType(
    'BowserTailAnchor',
    ['bhvBowserTailAnchor'],
  ),
  ObjectType(
    'Bowser',
    ['bhvBowser'],
  ),
  ObjectType(
    'BowserBodyAnchor',
    ['bhvBowserBodyAnchor'],
  ),
  ObjectType(
    'BowserFlameSpawn',
    ['bhvBowserFlameSpawn'],
  ),
  ObjectType(
    'TiltingBowserLavaPlatform',
    ['bhvTiltingBowserLavaPlatform'],
  ),
  ObjectType(
    'FallingBowserPlatform',
    ['bhvFallingBowserPlatform'],
  ),
  ObjectType(
    'BlueBowserFlame',
    ['bhvBlueBowserFlame'],
  ),
  ObjectType(
    'FlameFloatingLanding',
    ['bhvFlameFloatingLanding'],
  ),
  ObjectType(
    'BlueFlamesGroup',
    ['bhvBlueFlamesGroup'],
  ),
  ObjectType(
    'FlameBouncing',
    ['bhvFlameBouncing'],
  ),
  ObjectType(
    'FlameMovingForwardGrowing',
    ['bhvFlameMovingForwardGrowing'],
  ),
  ObjectType(
    'FlameBowser',
    ['bhvFlameBowser'],
  ),
  ObjectType(
    'FlameLargeBurningOut',
    ['bhvFlameLargeBurningOut'],
  ),
  ObjectType(
    'BlueFish',
    ['bhvBlueFish'],
  ),
  ObjectType(
    'TankFishGroups',
    ['bhvTankFishGroups'],
  ),
  ObjectType(
    'CheckerboardElevatorGroup',
    ['bhvCheckerboardElevatorGroup'],
  ),
  ObjectType(
    'CheckerboardPlatformSub',
    ['bhvCheckerboardPlatformSub'],
  ),
  ObjectType(
    'DoorKey1',
    ['bhvDoorKey1'],
  ),
  ObjectType(
    'DoorKey2',
    ['bhvDoorKey2'],
  ),
  ObjectType(
    'InvisibleObjectsUnderBridge',
    ['bhvInvisibleObjectsUnderBridge'],
  ),
  ObjectType(
    'WaterLevelPillar',
    ['bhvWaterLevelPillar'],
  ),
  ObjectType(
    'DddWarp',
    ['bhvDddWarp'],
  ),
  ObjectType(
    'MoatGrills',
    ['bhvMoatGrills'],
  ),
  ObjectType(
    'ClockMinuteHand',
    ['bhvClockMinuteHand'],
  ),
  ObjectType(
    'ClockHourHand',
    ['bhvClockHourHand'],
  ),
  ObjectType(
    'UkikiOpenCage',
    ['bhvUkikiOpenCage'],
  ),
  ObjectType(
    'Stub1D0C',
    ['bhvStub1D0C'],
  ),
  ObjectType(
    'LllRotatingHexagonalPlatform',
    ['bhvLllRotatingHexagonalPlatform'],
  ),
  ObjectType(
    'LllSinkingRockBlock',
    ['bhvLllSinkingRockBlock'],
  ),
  ObjectType(
    'Stub1D70',
    ['bhvStub1D70'],
  ),
  ObjectType(
    'LllMovingOctagonalMeshPlatform',
    ['bhvLllMovingOctagonalMeshPlatform'],
  ),
  ObjectType(
    'SnowBall',
    ['bhvSnowBall'],
  ),
  ObjectType(
    'LllRotatingBlockWithFireBars',
    ['bhvLllRotatingBlockWithFireBars'],
  ),
  ObjectType(
    'LllRotatingHexFlame',
    ['bhvLllRotatingHexFlame'],
  ),
  ObjectType(
    'LllWoodPiece',
    ['bhvLllWoodPiece'],
  ),
  ObjectType(
    'LllFloatingWoodBridge',
    ['bhvLllFloatingWoodBridge'],
  ),
  ObjectType(
    'VolcanoFlames',
    ['bhvVolcanoFlames'],
  ),
  ObjectType(
    'LllRotatingHexagonalRing',
    ['bhvLllRotatingHexagonalRing'],
  ),
  ObjectType(
    'LllSinkingRectangularPlatform',
    ['bhvLllSinkingRectangularPlatform'],
  ),
  ObjectType(
    'LllSinkingSquarePlatforms',
    ['bhvLllSinkingSquarePlatforms'],
  ),
  ObjectType(
    'LllTiltingSquarePlatform',
    ['bhvLllTiltingSquarePlatform'],
  ),
  ObjectType(
    'Unused1F30',
    ['bhvUnused1F30'],
  ),
  ObjectType(
    'KoopaShell',
    ['bhvKoopaShell'],
  ),
  ObjectType(
    'KoopaShellFlame',
    ['bhvKoopaShellFlame'],
  ),
  ObjectType(
    'ToxBox',
    ['bhvToxBox'],
  ),
  ObjectType(
    'PiranhaPlant2',
    ['bhvPiranhaPlant2'],
  ),
  ObjectType(
    'LllHexagonalMesh',
    ['bhvLllHexagonalMesh'],
  ),
  ObjectType(
    'LllBowserPuzzlePiece',
    ['bhvLllBowserPuzzlePiece'],
  ),
  ObjectType(
    'LllBowserPuzzle',
    ['bhvLllBowserPuzzle'],
  ),
  ObjectType(
    'TuxiesMother',
    ['bhvTuxiesMother'],
  ),
  ObjectType(
    'PenguinBaby',
    ['bhvPenguinBaby'],
  ),
  ObjectType(
    'Unused20E0',
    ['bhvUnused20E0'],
  ),
  ObjectType(
    'SmallPenguin',
    ['bhvSmallPenguin'],
  ),
  ObjectType(
    'Fish2',
    ['bhvFish2'],
  ),
  ObjectType(
    'Fish3',
    ['bhvFish3'],
  ),
  ObjectType(
    'LargeFishGroup',
    ['bhvLargeFishGroup'],
  ),
  ObjectType(
    'FishCommon',
    ['bhvFishCommon'],
  ),
  ObjectType(
    'FishGroup2',
    ['bhvFishGroup2'],
  ),
  ObjectType(
    'WdwExpressElevator',
    ['bhvWdwExpressElevator'],
  ),
  ObjectType(
    'WdwExpressElevatorPlatform',
    ['bhvWdwExpressElevatorPlatform'],
  ),
  ObjectType(
    'ChirpChirp',
    ['bhvChirpChirp'],
  ),
  ObjectType(
    'ChirpChirpUnused',
    ['bhvChirpChirpUnused'],
  ),
  ObjectType(
    'Bub',
    ['bhvBub'],
  ),
  ObjectType(
    'ExclamationBox',
    ['bhvExclamationBox'],
  ),
  ObjectType(
    'RotatingExclamationMark',
    ['bhvRotatingExclamationMark'],
  ),
  ObjectType(
    'SoundSpawner',
    ['bhvSoundSpawner'],
  ),
  ObjectType(
    'RockSolid',
    ['bhvRockSolid'],
  ),
  ObjectType(
    'BowserSubDoor',
    ['bhvBowserSubDoor'],
  ),
  ObjectType(
    'BowsersSub',
    ['bhvBowsersSub'],
  ),
  ObjectType(
    'SushiShark',
    ['bhvSushiShark'],
  ),
  ObjectType(
    'SushiSharkCollisionChild',
    ['bhvSushiSharkCollisionChild'],
  ),
  ObjectType(
    'JrbSlidingBox',
    ['bhvJrbSlidingBox'],
  ),
  ObjectType(
    'ShipPart3',
    ['bhvShipPart3'],
  ),
  ObjectType(
    'InSunkenShip3',
    ['bhvInSunkenShip3'],
  ),
  ObjectType(
    'SunkenShipPart',
    ['bhvSunkenShipPart'],
  ),
  ObjectType(
    'Unused243C',
    ['bhvUnused243C'],
  ),
  ObjectType(
    'SunkenShipPart2',
    ['bhvSunkenShipPart2'],
  ),
  ObjectType(
    'InSunkenShip',
    ['bhvInSunkenShip'],
  ),
  ObjectType(
    'InSunkenShip2',
    ['bhvInSunkenShip2'],
  ),
  ObjectType(
    'MarioDustGenerator',
    ['bhvMarioDustGenerator'],
  ),
  ObjectType(
    'WhitePuff1',
    ['bhvWhitePuff1'],
  ),
  ObjectType(
    'WhitePuff2',
    ['bhvWhitePuff2'],
  ),
  ObjectType(
    'WhitePuffSmoke2',
    ['bhvWhitePuffSmoke2'],
  ),
  ObjectType(
    'PurpleSwitchHiddenBoxes',
    ['bhvPurpleSwitchHiddenBoxes'],
  ),
  ObjectType(
    'BlueCoinSwitch',
    ['bhvBlueCoinSwitch'],
  ),
  ObjectType(
    'HiddenBlueCoin',
    ['bhvHiddenBlueCoin'],
  ),
  ObjectType(
    'OpenableCageDoor',
    ['bhvOpenableCageDoor'],
  ),
  ObjectType(
    'OpenableGrill',
    ['bhvOpenableGrill'],
  ),
  ObjectType(
    'WaterLevelDiamond',
    ['bhvWaterLevelDiamond'],
  ),
  ObjectType(
    'InitializeChangingWaterLevel',
    ['bhvInitializeChangingWaterLevel'],
  ),
  ObjectType(
    'TornadoSandParticle',
    ['bhvTornadoSandParticle'],
  ),
  ObjectType(
    'Tornado',
    ['bhvTornado'],
  ),
  ObjectType(
    'SpawnBigBoo',
    ['bhvSpawnBigBoo'],
  ),
  ObjectType(
    'AnimatedTexture',
    ['bhvAnimatedTexture'],
  ),
  ObjectType(
    'BooInCastle',
    ['bhvBooInCastle'],
  ),
  ObjectType(
    'BooWithCage',
    ['bhvBooWithCage'],
  ),
  ObjectType(
    'PatrollingBoo',
    ['bhvPatrollingBoo'],
  ),
  ObjectType(
    'SpawnedBoo',
    ['bhvSpawnedBoo'],
  ),
  ObjectType(
    'BooGivingStar',
    ['bhvBooGivingStar'],
  ),
  ObjectType(
    'BooGroup',
    ['bhvBooGroup'],
  ),
  ObjectType(
    'Boo3',
    ['bhvBoo3'],
  ),
  ObjectType(
    'SpawnedBoo2',
    ['bhvSpawnedBoo2'],
  ),
  ObjectType(
    'Boo2',
    ['bhvBoo2'],
  ),
  ObjectType(
    'HiddenStaircaseStep',
    ['bhvHiddenStaircaseStep'],
  ),
  ObjectType(
    'BooBossSpawnedBridge',
    ['bhvBooBossSpawnedBridge'],
  ),
  ObjectType(
    'BbhTiltFloorPlatforms',
    ['bhvBbhTiltFloorPlatforms'],
  ),
  ObjectType(
    'TumblingBookshelf',
    ['bhvTumblingBookshelf'],
  ),
  ObjectType(
    'MeshElevator',
    ['bhvMeshElevator'],
  ),
  ObjectType(
    'RotatingMerryGoRound',
    ['bhvRotatingMerryGoRound'],
  ),
  ObjectType(
    'PlaysMusicTrackWhenTouched',
    ['bhvPlaysMusicTrackWhenTouched'],
  ),
  ObjectType(
    'InsideCannon',
    ['bhvInsideCannon'],
  ),
  ObjectType(
    'BetaFollowingCirclingObj',
    ['bhvBetaFollowingCirclingObj'],
  ),
  ObjectType(
    'StaticCheckeredPlatform',
    ['bhvStaticCheckeredPlatform'],
  ),
  ObjectType(
    'Unused2A10',
    ['bhvUnused2A10'],
  ),
  ObjectType(
    'UnusedFakeStar',
    ['bhvUnusedFakeStar'],
  ),
  ObjectType(
    'StaticObject',
    ['bhvStaticObject'],
  ),
  ObjectType(
    'Unused2A54',
    ['bhvUnused2A54'],
  ),
  ObjectType(
    'CastleFloorTrap',
    ['bhvCastleFloorTrap'],
  ),
  ObjectType(
    'FloorTrapInCastle',
    ['bhvFloorTrapInCastle'],
  ),
  ObjectType(
    'Tree',
    ['bhvTree'],
  ),
  ObjectType(
    'PowerupSparkles1',
    ['bhvPowerupSparkles1'],
  ),
  ObjectType(
    'PowerupSparkles2',
    ['bhvPowerupSparkles2'],
  ),
  ObjectType(
    'SpecialTripleJumpSparkles',
    ['bhvSpecialTripleJumpSparkles'],
  ),
  ObjectType(
    'SomeGfx',
    ['bhvSomeGfx'],
  ),
  ObjectType(
    'Scuttlebug',
    ['bhvScuttlebug'],
  ),
  ObjectType(
    'ScuttlebugSpawn',
    ['bhvScuttlebugSpawn'],
  ),
  ObjectType(
    'WhompKingBoss',
    ['bhvWhompKingBoss'],
  ),
  ObjectType(
    'SmallWhomp',
    ['bhvSmallWhomp'],
  ),
  ObjectType(
    'WaterSplash',
    ['bhvWaterSplash'],
  ),
  ObjectType(
    'WaterDrops',
    ['bhvWaterDrops'],
  ),
  ObjectType(
    'WaterSurfaceWhiteWave',
    ['bhvWaterSurfaceWhiteWave'],
  ),
  ObjectType(
    'ObjectBubbleRipples',
    ['bhvObjectBubbleRipples'],
  ),
  ObjectType(
    'SurfaceWaves',
    ['bhvSurfaceWaves'],
  ),
  ObjectType(
    'WaterSurfaceWhiteWave2',
    ['bhvWaterSurfaceWhiteWave2'],
  ),
  ObjectType(
    'WavesGenerator',
    ['bhvWavesGenerator'],
  ),
  ObjectType(
    'SurfaceWaveShrinking',
    ['bhvSurfaceWaveShrinking'],
  ),
  ObjectType(
    'WaterType',
    ['bhvWaterType'],
  ),
  ObjectType(
    'WaveTrailOnSurface',
    ['bhvWaveTrailOnSurface'],
  ),
  ObjectType(
    'TinyWhiteWindParticle',
    ['bhvTinyWhiteWindParticle'],
  ),
  ObjectType(
    'WindParticle',
    ['bhvWindParticle'],
  ),
  ObjectType(
    'SnowmanWindBlowing',
    ['bhvSnowmanWindBlowing'],
  ),
  ObjectType(
    'WalkingPenguin',
    ['bhvWalkingPenguin'],
  ),
  ObjectType(
    'YellowBall',
    ['bhvYellowBall'],
  ),
  ObjectType(
    'Mario Object',
    ['bhvMario'],
  ),
  ObjectType(
    'ToadMessage',
    ['bhvToadMessage'],
  ),
  ObjectType(
    'UnlockDoorStar',
    ['bhvUnlockDoorStar'],
  ),
  ObjectType(
    'Warps60',
    ['bhvWarps60'],
  ),
  ObjectType(
    'Warps64',
    ['bhvWarps64'],
  ),
  ObjectType(
    'Warps68',
    ['bhvWarps68'],
  ),
  ObjectType(
    'Warps6C',
    ['bhvWarps6C'],
  ),
  ObjectType(
    'Warps70',
    ['bhvWarps70'],
  ),
  ObjectType(
    'Warps74',
    ['bhvWarps74'],
  ),
  ObjectType(
    'Warps78',
    ['bhvWarps78'],
  ),
  ObjectType(
    'Warps7C',
    ['bhvWarps7C'],
  ),
  ObjectType(
    'Warps80',
    ['bhvWarps80'],
  ),
  ObjectType(
    'Warps84',
    ['bhvWarps84'],
  ),
  ObjectType(
    'Warps88',
    ['bhvWarps88'],
  ),
  ObjectType(
    'Warps8C',
    ['bhvWarps8C'],
  ),
  ObjectType(
    'Warps90',
    ['bhvWarps90'],
  ),
  ObjectType(
    'Warps94',
    ['bhvWarps94'],
  ),
  ObjectType(
    'RandomAnimatedTexture',
    ['bhvRandomAnimatedTexture'],
  ),
  ObjectType(
    'YellowBackgroundInMenu',
    ['bhvYellowBackgroundInMenu'],
  ),
  ObjectType(
    'MenuButton',
    ['bhvMenuButton'],
  ),
  ObjectType(
    'MenuButtonManager',
    ['bhvMenuButtonManager'],
  ),
  ObjectType(
    'StarInActSelector',
    ['bhvStarInActSelector'],
  ),
  ObjectType(
    'ActSelector',
    ['bhvActSelector'],
  ),
  ObjectType(
    'MovingYellowCoin',
    ['bhvMovingYellowCoin'],
  ),
  ObjectType(
    'MovingBlueCoin',
    ['bhvMovingBlueCoin'],
  ),
  ObjectType(
    'BlueCoinSliding',
    ['bhvBlueCoinSliding'],
  ),
  ObjectType(
    'BlueCoinJumping',
    ['bhvBlueCoinJumping'],
  ),
  ObjectType(
    'Seaweed',
    ['bhvSeaweed'],
  ),
  ObjectType(
    'SeaweedBundle',
    ['bhvSeaweedBundle'],
  ),
  ObjectType(
    'Bobomb',
    ['bhvBobomb'],
  ),
  ObjectType(
    'BobombFuseSmoke',
    ['bhvBobombFuseSmoke'],
  ),
  ObjectType(
    'BobombBuddy',
    ['bhvBobombBuddy'],
  ),
  ObjectType(
    'BobombBuddyOpensCannon',
    ['bhvBobombBuddyOpensCannon'],
  ),
  ObjectType(
    'CannonClosed',
    ['bhvCannonClosed'],
  ),
  ObjectType(
    'Whirlpool',
    ['bhvWhirlpool'],
  ),
  ObjectType(
    'JetStream',
    ['bhvJetStream'],
  ),
  ObjectType(
    'MessagePanel',
    ['bhvMessagePanel'],
  ),
  ObjectType(
    'SignOnWall',
    ['bhvSignOnWall'],
  ),
  ObjectType(
    'AmpHoming',
    ['bhvAmpHoming'],
  ),
  ObjectType(
    'AmpCircling',
    ['bhvAmpCircling'],
  ),
  ObjectType(
    'Butterfly',
    ['bhvButterfly'],
  ),
  ObjectType(
    'Hoot',
    ['bhvHoot'],
  ),
  ObjectType(
    'BetaGreenShell',
    ['bhvBetaGreenShell'],
  ),
  ObjectType(
    'CarrySomething1',
    ['bhvCarrySomething1'],
  ),
  ObjectType(
    'CarrySomething2',
    ['bhvCarrySomething2'],
  ),
  ObjectType(
    'CarrySomething3',
    ['bhvCarrySomething3'],
  ),
  ObjectType(
    'CarrySomething4',
    ['bhvCarrySomething4'],
  ),
  ObjectType(
    'CarrySomething5',
    ['bhvCarrySomething5'],
  ),
  ObjectType(
    'CarrySomething6',
    ['bhvCarrySomething6'],
  ),
  ObjectType(
    'ObjectBubble',
    ['bhvObjectBubble'],
  ),
  ObjectType(
    'ObjectWaterWave',
    ['bhvObjectWaterWave'],
  ),
  ObjectType(
    'Explosion',
    ['bhvExplosion'],
  ),
  ObjectType(
    'BobombBullyDeathSmoke',
    ['bhvBobombBullyDeathSmoke'],
  ),
  ObjectType(
    'Smoke',
    ['bhvSmoke'],
  ),
  ObjectType(
    'BobombExplosionBubble',
    ['bhvBobombExplosionBubble'],
  ),
  ObjectType(
    'BobombExplosionBubble3600',
    ['bhvBobombExplosionBubble3600'],
  ),
  ObjectType(
    'Respawner',
    ['bhvRespawner'],
  ),
  ObjectType(
    'SmallBully',
    ['bhvSmallBully'],
  ),
  ObjectType(
    'BigBully',
    ['bhvBigBully'],
  ),
  ObjectType(
    'BigBullyWithMinions',
    ['bhvBigBullyWithMinions'],
  ),
  ObjectType(
    'SmallChillBully',
    ['bhvSmallChillBully'],
  ),
  ObjectType(
    'BigChillBully',
    ['bhvBigChillBully'],
  ),
  ObjectType(
    'JetStreamRingSpawner',
    ['bhvJetStreamRingSpawner'],
  ),
  ObjectType(
    'JetStreamWaterRing',
    ['bhvJetStreamWaterRing'],
  ),
  ObjectType(
    'MantaRayWaterRing',
    ['bhvMantaRayWaterRing'],
  ),
  ObjectType(
    'MantaRayRingManager',
    ['bhvMantaRayRingManager'],
  ),
  ObjectType(
    'BowserBomb',
    ['bhvBowserBomb'],
  ),
  ObjectType(
    'BowserBombExplosion',
    ['bhvBowserBombExplosion'],
  ),
  ObjectType(
    'BowserBombSmoke',
    ['bhvBowserBombSmoke'],
  ),
  ObjectType(
    'CelebrationStar',
    ['bhvCelebrationStar'],
  ),
  ObjectType(
    'CelebrationStarSparkle',
    ['bhvCelebrationStarSparkle'],
  ),
  ObjectType(
    'StarKeyCollectionPuffSpawner',
    ['bhvStarKeyCollectionPuffSpawner'],
  ),
  ObjectType(
    'LllDrawbridgeSpawner',
    ['bhvLllDrawbridgeSpawner'],
  ),
  ObjectType(
    'LllDrawbridge',
    ['bhvLllDrawbridge'],
  ),
  ObjectType(
    'SmallBomp',
    ['bhvSmallBomp'],
  ),
  ObjectType(
    'LargeBomp',
    ['bhvLargeBomp'],
  ),
  ObjectType(
    'WfSlidingPlatform',
    ['bhvWfSlidingPlatform'],
  ),
  ObjectType(
    'Moneybag',
    ['bhvMoneybag'],
  ),
  ObjectType(
    'MoneybagHidden',
    ['bhvMoneybagHidden'],
  ),
  ObjectType(
    'PitBowlingBall',
    ['bhvPitBowlingBall'],
  ),
  ObjectType(
    'FreeBowlingBall',
    ['bhvFreeBowlingBall'],
  ),
  ObjectType(
    'BowlingBall',
    ['bhvBowlingBall'],
  ),
  ObjectType(
    'TtmBowlingBallSpawner',
    ['bhvTtmBowlingBallSpawner'],
  ),
  ObjectType(
    'BobBowlingBallSpawner',
    ['bhvBobBowlingBallSpawner'],
  ),
  ObjectType(
    'ThiBowlingBallSpawner',
    ['bhvThiBowlingBallSpawner'],
  ),
  ObjectType(
    'RrCruiserWing',
    ['bhvRrCruiserWing'],
  ),
  ObjectType(
    'Spindel',
    ['bhvSpindel'],
  ),
  ObjectType(
    'SslMovingPyramidWall',
    ['bhvSslMovingPyramidWall'],
  ),
  ObjectType(
    'PyramidElevator',
    ['bhvPyramidElevator'],
  ),
  ObjectType(
    'PyramidElevatorMetalBalls',
    ['bhvPyramidElevatorMetalBalls'],
  ),
  ObjectType(
    'PyramidTop',
    ['bhvPyramidTop'],
  ),
  ObjectType(
    'PyramidTopExplosion',
    ['bhvPyramidTopExplosion'],
  ),
  ObjectType(
    'CollisionBoxSubbehavior',
    ['bhvCollisionBoxSubbehavior'],
  ),
  ObjectType(
    'WaterfallSoundLoop',
    ['bhvWaterfallSoundLoop'],
  ),
  ObjectType(
    'VolcanoSoundLoop',
    ['bhvVolcanoSoundLoop'],
  ),
  ObjectType(
    'CastleFlagWaving',
    ['bhvCastleFlagWaving'],
  ),
  ObjectType(
    'BirdsSoundLoop',
    ['bhvBirdsSoundLoop'],
  ),
  ObjectType(
    'AmbientSounds',
    ['bhvAmbientSounds'],
  ),
  ObjectType(
    'SandSoundLoop',
    ['bhvSandSoundLoop'],
  ),
  ObjectType(
    'HiddenAt120Stars',
    ['bhvHiddenAt120Stars'],
  ),
  ObjectType(
    'SnowmansBottom',
    ['bhvSnowmansBottom'],
  ),
  ObjectType(
    'SnowmansHead',
    ['bhvSnowmansHead'],
  ),
  ObjectType(
    'SnowmansBodyCheckpoint',
    ['bhvSnowmansBodyCheckpoint'],
  ),
  ObjectType(
    'BigSnowmanWhole',
    ['bhvBigSnowmanWhole'],
  ),
  ObjectType(
    'BigBoulder',
    ['bhvBigBoulder'],
  ),
  ObjectType(
    'BigBoulderGenerator',
    ['bhvBigBoulderGenerator'],
  ),
  ObjectType(
    'WingCap',
    ['bhvWingCap'],
  ),
  ObjectType(
    'MetalCap',
    ['bhvMetalCap'],
  ),
  ObjectType(
    'NormalCap',
    ['bhvNormalCap'],
  ),
  ObjectType(
    'VanishCap',
    ['bhvVanishCap'],
  ),
  ObjectType(
    'Star',
    ['bhvStar'],
  ),
  ObjectType(
    'StarSpawnCoordinates',
    ['bhvStarSpawnCoordinates'],
  ),
  ObjectType(
    'HiddenRedCoinStar',
    ['bhvHiddenRedCoinStar'],
  ),
  ObjectType(
    'RedCoin',
    ['bhvRedCoin'],
  ),
  ObjectType(
    'BowserCourseRedCoinStar',
    ['bhvBowserCourseRedCoinStar'],
  ),
  ObjectType(
    'HiddenStar',
    ['bhvHiddenStar'],
  ),
  ObjectType(
    'HiddenStarTrigger',
    ['bhvHiddenStarTrigger'],
  ),
  ObjectType(
    'TtmRollingLog',
    ['bhvTtmRollingLog'],
  ),
  ObjectType(
    'LllVolcanoFallingTrap',
    ['bhvLllVolcanoFallingTrap'],
  ),
  ObjectType(
    'LllRollingLog',
    ['bhvLllRollingLog'],
  ),
  ObjectType(
    '1upWalking',
    ['bhv1upWalking'],
  ),
  ObjectType(
    '1upRunningAway',
    ['bhv1upRunningAway'],
  ),
  ObjectType(
    '1upSliding',
    ['bhv1upSliding'],
  ),
  ObjectType(
    '1Up',
    ['bhv1Up'],
  ),
  ObjectType(
    '1upJumpOnApproach',
    ['bhv1upJumpOnApproach'],
  ),
  ObjectType(
    'Hidden1up',
    ['bhvHidden1up'],
  ),
  ObjectType(
    'Hidden1upTrigger',
    ['bhvHidden1upTrigger'],
  ),
  ObjectType(
    'Hidden1upInPole',
    ['bhvHidden1upInPole'],
  ),
  ObjectType(
    'Hidden1upInPoleTrigger',
    ['bhvHidden1upInPoleTrigger'],
  ),
  ObjectType(
    'Hidden1upInPoleSpawner',
    ['bhvHidden1upInPoleSpawner'],
  ),
  ObjectType(
    'ControllablePlatform',
    ['bhvControllablePlatform'],
  ),
  ObjectType(
    'ControllablePlatformSub',
    ['bhvControllablePlatformSub'],
  ),
  ObjectType(
    'BreakableBoxSmall',
    ['bhvBreakableBoxSmall'],
  ),
  ObjectType(
    'SlidingSnowMound',
    ['bhvSlidingSnowMound'],
  ),
  ObjectType(
    'SnowMoundSpawn',
    ['bhvSnowMoundSpawn'],
  ),
  ObjectType(
    'WdwSquareFloatingPlatform',
    ['bhvWdwSquareFloatingPlatform'],
  ),
  ObjectType(
    'WdwRectangularFloatingPlatform',
    ['bhvWdwRectangularFloatingPlatform'],
  ),
  ObjectType(
    'JrbFloatingPlatform',
    ['bhvJrbFloatingPlatform'],
  ),
  ObjectType(
    'ArrowLift',
    ['bhvArrowLift'],
  ),
  ObjectType(
    'OrangeNumber',
    ['bhvOrangeNumber'],
  ),
  ObjectType(
    'MantaRay',
    ['bhvMantaRay'],
  ),
  ObjectType(
    'FallingPillar',
    ['bhvFallingPillar'],
  ),
  ObjectType(
    'SomeSubojbjectOfFallingPillar',
    ['bhvSomeSubojbjectOfFallingPillar'],
  ),
  ObjectType(
    'PillarBase',
    ['bhvPillarBase'],
  ),
  ObjectType(
    'JrbFloatingBox',
    ['bhvJrbFloatingBox'],
  ),
  ObjectType(
    'OscillatingPendulum',
    ['bhvOscillatingPendulum'],
  ),
  ObjectType(
    'TreasureChestsShip',
    ['bhvTreasureChestsShip'],
  ),
  ObjectType(
    'TreasureChestsJrb',
    ['bhvTreasureChestsJrb'],
  ),
  ObjectType(
    'TreasureChests',
    ['bhvTreasureChests'],
  ),
  ObjectType(
    'TreasureChestBottom',
    ['bhvTreasureChestBottom'],
  ),
  ObjectType(
    'TreasureChestTop',
    ['bhvTreasureChestTop'],
  ),
  ObjectType(
    'Mips',
    ['bhvMips'],
  ),
  ObjectType(
    'Yoshi',
    ['bhvYoshi'],
  ),
  ObjectType(
    'Koopa',
    ['bhvKoopa'],
  ),
  ObjectType(
    'KoopaRaceEndpoint',
    ['bhvKoopaRaceEndpoint'],
  ),
  ObjectType(
    'KoopaFlag',
    ['bhvKoopaFlag'],
  ),
  ObjectType(
    'Pokey',
    ['bhvPokey'],
  ),
  ObjectType(
    'PokeyBodyPart',
    ['bhvPokeyBodyPart'],
  ),
  ObjectType(
    'Swoop',
    ['bhvSwoop'],
  ),
  ObjectType(
    'FlyGuy',
    ['bhvFlyGuy'],
  ),
  ObjectType(
    'Goomba',
    ['bhvGoomba'],
  ),
  ObjectType(
    'GoombaTripletSpawner',
    ['bhvGoombaTripletSpawner'],
  ),
  ObjectType(
    'ChainChomp',
    ['bhvChainChomp'],
  ),
  ObjectType(
    'ChainChompChainPart',
    ['bhvChainChompChainPart'],
  ),
  ObjectType(
    'WoodenPost',
    ['bhvWoodenPost'],
  ),
  ObjectType(
    'ChainChompGate',
    ['bhvChainChompGate'],
  ),
  ObjectType(
    'Wiggler',
    ['bhvWiggler'],
  ),
  ObjectType(
    'WigglerBodyPart',
    ['bhvWigglerBodyPart'],
  ),
  ObjectType(
    'EnemyLakitu',
    ['bhvEnemyLakitu'],
  ),
  ObjectType(
    'CameraLakitu',
    ['bhvCameraLakitu'],
  ),
  ObjectType(
    'Cloud',
    ['bhvCloud'],
  ),
  ObjectType(
    'CloudPart',
    ['bhvCloudPart'],
  ),
  ObjectType(
    'Spiny',
    ['bhvSpiny'],
  ),
  ObjectType(
    'MontyMole',
    ['bhvMontyMole'],
  ),
  ObjectType(
    'MontyMoleHole',
    ['bhvMontyMoleHole'],
  ),
  ObjectType(
    'MontyMoleRock',
    ['bhvMontyMoleRock'],
  ),
  ObjectType(
    'PlatformOnTrack',
    ['bhvPlatformOnTrack'],
  ),
  ObjectType(
    'TrackBall',
    ['bhvTrackBall'],
  ),
  ObjectType(
    'SeesawPlatform',
    ['bhvSeesawPlatform'],
  ),
  ObjectType(
    'FerrisWheelAxle',
    ['bhvFerrisWheelAxle'],
  ),
  ObjectType(
    'FerrisWheelPlatform',
    ['bhvFerrisWheelPlatform'],
  ),
  ObjectType(
    'WaterBombSpawner',
    ['bhvWaterBombSpawner'],
  ),
  ObjectType(
    'WaterBomb',
    ['bhvWaterBomb'],
  ),
  ObjectType(
    'WaterBombShadow',
    ['bhvWaterBombShadow'],
  ),
  ObjectType(
    'TTCRotatingSolid',
    ['bhvTTCRotatingSolid'],
  ),
  ObjectType(
    'TTCPendulum',
    ['bhvTTCPendulum'],
  ),
  ObjectType(
    'TTCTreadmill',
    ['bhvTTCTreadmill'],
  ),
  ObjectType(
    'TTCMovingBar',
    ['bhvTTCMovingBar'],
  ),
  ObjectType(
    'TTCCog',
    ['bhvTTCCog'],
  ),
  ObjectType(
    'TTCPitBlock',
    ['bhvTTCPitBlock'],
  ),
  ObjectType(
    'TTCElevator',
    ['bhvTTCElevator'],
  ),
  ObjectType(
    'TTC2DRotator',
    ['bhvTTC2DRotator'],
  ),
  ObjectType(
    'TTCSpinner',
    ['bhvTTCSpinner'],
  ),
  ObjectType(
    'MrBlizzard',
    ['bhvMrBlizzard'],
  ),
  ObjectType(
    'MrBlizzardSnowball',
    ['bhvMrBlizzardSnowball'],
  ),
  ObjectType(
    'SlidingPlatform2',
    ['bhvSlidingPlatform2'],
  ),
  ObjectType(
    'OctagonalPlatformRotating',
    ['bhvOctagonalPlatformRotating'],
  ),
  ObjectType(
    'AnimatesOnFloorSwitchPress',
    ['bhvAnimatesOnFloorSwitchPress'],
  ),
  ObjectType(
    'ActivatedBackAndForthPlatform',
    ['bhvActivatedBackAndForthPlatform'],
  ),
  ObjectType(
    'RecoveryHeart',
    ['bhvRecoveryHeart'],
  ),
  ObjectType(
    'WaterBombCannon',
    ['bhvWaterBombCannon'],
  ),
  ObjectType(
    'CannonBarrelBubbles',
    ['bhvCannonBarrelBubbles'],
  ),
  ObjectType(
    'Unagi',
    ['bhvUnagi'],
  ),
  ObjectType(
    'UnagiSubobject',
    ['bhvUnagiSubobject'],
  ),
  ObjectType(
    'Dorrie',
    ['bhvDorrie'],
  ),
  ObjectType(
    'HauntedChair',
    ['bhvHauntedChair'],
  ),
  ObjectType(
    'MadPiano',
    ['bhvMadPiano'],
  ),
  ObjectType(
    'FlyingBookend',
    ['bhvFlyingBookend'],
  ),
  ObjectType(
    'BookendSpawn',
    ['bhvBookendSpawn'],
  ),
  ObjectType(
    'BookshelfThing',
    ['bhvBookshelfThing'],
  ),
  ObjectType(
    'BookSwitch',
    ['bhvBookSwitch'],
  ),
  ObjectType(
    'FirePiranhaPlant',
    ['bhvFirePiranhaPlant'],
  ),
  ObjectType(
    'SmallPiranhaFlame',
    ['bhvSmallPiranhaFlame'],
  ),
  ObjectType(
    'FireSpitter',
    ['bhvFireSpitter'],
  ),
  ObjectType(
    'FlyguyFlame',
    ['bhvFlyguyFlame'],
  ),
  ObjectType(
    'Snufit',
    ['bhvSnufit'],
  ),
  ObjectType(
    'SnufitBalls',
    ['bhvSnufitBalls'],
  ),
  ObjectType(
    'HorizontalGrindel',
    ['bhvHorizontalGrindel'],
  ),
  ObjectType(
    'EyerokBoss',
    ['bhvEyerokBoss'],
  ),
  ObjectType(
    'EyerokHand',
    ['bhvEyerokHand'],
  ),
  ObjectType(
    'Klepto',
    ['bhvKlepto'],
  ),
  ObjectType(
    'Bird',
    ['bBird'],
  ),
  ObjectType(
    'RacingPenguin',
    ['bhvRacingPenguin'],
  ),
  ObjectType(
    'PenguinRaceFinishLine',
    ['bhvPenguinRaceFinishLine'],
  ),
  ObjectType(
    'PenguinRaceShortcutCheck',
    ['bhvPenguinRaceShortcutCheck'],
  ),
  ObjectType(
    'HauntedRoomCheck',
    ['bhvHauntedRoomCheck'],
  ),
  ObjectType(
    'HauntedRoomCheckSubobject',
    ['bhvHauntedRoomCheckSubobject'],
  ),
  ObjectType(
    'ClamShell',
    ['bhvClamShell'],
  ),
  ObjectType(
    'Skeeter',
    ['bhvSkeeter'],
  ),
  ObjectType(
    'SkeeterWave',
    ['bhvSkeeterWave'],
  ),
  ObjectType(
    'SwingPlatform',
    ['bhvSwingPlatform'],
  ),
  ObjectType(
    'DonutPlatformSpawner',
    ['bhvDonutPlatformSpawner'],
  ),
  ObjectType(
    'DonutPlatform',
    ['bhvDonutPlatform'],
  ),
  ObjectType(
    'DDDPole',
    ['bhvDDDPole'],
  ),
  ObjectType(
    'RedCoinStarMarker',
    ['bhvRedCoinStarMarker'],
  ),
  ObjectType(
    'TripletButterfly',
    ['bhvTripletButterfly'],
  ),
  ObjectType(
    'Bubba',
    ['bhvBubba'],
  ),
  ObjectType(
    'BeginningLakitu',
    ['bhvBeginningLakitu'],
  ),
  ObjectType(
    'BeginningPeach',
    ['bhvBeginningPeach'],
  ),
  ObjectType(
    'EndBirds1',
    ['bhvEndBirds1'],
  ),
  ObjectType(
    'EndBirds2',
    ['bhvEndBirds2'],
  ),
  ObjectType(
    'IntroScene',
    ['bhvIntroScene'],
  ),
]
