[package]
name = "fast3d"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1.3.2"
bytemuck = "1.9.1"
derivative = "2.2.0"
num_enum = "0.5.7"
wgpu = { workspace = true, optional = true }
