from wafel.ui.object_slots import *
from wafel.ui.joystick_control import *
from wafel.ui.variable_value import *
from wafel.ui.labeled_variable import *
from wafel.ui.tabs import *
from wafel.ui.frame_slider import *
from wafel.ui.variable_cell import *
from wafel.ui.loading_bar import *
from wafel.ui.game_view import *
from wafel.ui.input_text_with_error import *
