[package]
name = "wafel_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.29"
egui = "0.22.0"
once_cell = "1.18.0"
pollster = "0.3.0"
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.17"
wgpu = "0.17.0"
winit = "0.28.6"
