[package]
name = "wafel_data_type"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "1.9.1", features = ["serde"] }
serde = { version = "1.0.137", features = ["derive", "rc"] }
