[package]
name = "wafel_sm64"
version = "0.1.0"
edition = "2021"

[dependencies]
wafel_data_access = { path = "../wafel_data_access" }
wafel_data_type = { path = "../wafel_data_type" }
wafel_layout = { path = "../wafel_layout" }
wafel_memory = { path = "../wafel_memory" }
