[package]
name = "wafel_viz"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.9.1"
env_logger = "0.9.0"
futures = "0.3.21"
once_cell = "1.12.0"
wafel_api = { path = "../wafel_api" }
wafel_data_type = { path = "../wafel_data_type" }
wafel_layout = { path = "../wafel_layout" }
wafel_memory = { path = "../wafel_memory" }
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
winit = "0.26.1"
