[package]
name = "wafel_viz"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.12.0"
wafel_data_type = { path = "../wafel_data_type" }
wafel_layout = { path = "../wafel_layout" }
wafel_memory = { path = "../wafel_memory" }
wgpu = "0.12.0"
