[package]
name = "wafel_app_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.22.0"
egui_dock = "0.6.3"
itertools = "0.11.0"
log = "0.4.20"
wafel_api = { version = "0.1.0", path = "../wafel_api" }
