[package]
name = "wafel_data_access"
version = "0.1.0"
edition = "2021"

[dependencies]
wafel_data_type = { path = "../wafel_data_type" }
wafel_layout = { path = "../wafel_layout" }
wafel_memory = { path = "../wafel_memory" }
wafel_data_access_derive = { path = "../wafel_data_access_derive" }
