name: Release

on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo build --release

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - run: pip install pipenv

      - run: |
          pipenv install --dev --python 3.7
          pipenv run python setup.py bdist_wheel
          pipenv run pip install --find-links=dist wafel --upgrade
          cd wafel_layout
          pipenv run python -c "import wafel"
          cd ..
          pipenv --rm
          cargo clean --target x86_64-pc-windows-msvc
      - run: |
          pipenv install --dev --python 3.8
          pipenv run python setup.py bdist_wheel
          pipenv run pip install --find-links=dist wafel --upgrade
          cd wafel_layout
          pipenv run python -c "import wafel"
          cd ..
          pipenv --rm
          cargo clean --target x86_64-pc-windows-msvc
      - run: |
          pipenv install --dev --python 3.9
          pipenv run python setup.py bdist_wheel
          pipenv run pip install --find-links=dist wafel --upgrade
          cd wafel_layout
          pipenv run python -c "import wafel"
          cd ..
          pipenv --rm
          cargo clean --target x86_64-pc-windows-msvc
      - run: |
          pipenv install --dev --python 3.10
          pipenv run python setup.py bdist_wheel
          pipenv run pip install --find-links=dist wafel --upgrade
          cd wafel_layout
          pipenv run python -c "import wafel"
          cd ..

      - run: pipenv run python build.py dist

      - uses: actions/upload-artifact@v2
        with:
          name: win_x64
          path: build/dist/*
