[package]
name = "wafel_layout"
version = "0.1.0"
edition = "2018"

[dependencies]
wafel_data_type = { path = "../wafel_data_type" }
object = "0.25.3"
gimli = "0.28.1"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_json = "1.0.64"
indexmap = "1.9.1"
